language: node_js
node_js:
  - 14
# branches:
#   only:
#     - master
addons:
  sonarcloud:
    organization: "jo3-w3b-d3v"
    token:
      secure: ebad63f56ea351c135ea1f697f4c83233be7de0b
before_script:
  - npm run-script build:setup
script: 
  - npm run-script test
  - npm run-script lint
  - npm audit 
  - npm run-script build:setup
  - npx dependency-check ./package.json --unused --no-dev ./src/bin/www
  - npm run-script retire 
  - sonar-scanner
  # - npm run-script sonar