name: Continuous Integration & Deployment
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ## Just to make sure that it can build with multiple versions of node.
        node-version: [8.x, 10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: NPM Local Setup
        run: npm run-script build:setup
      - name: Run Tests
        run: npm run-script test
      - name: Run Lint
        run: npm run lint 
      - name: NPM Audit
        run: npm audit 
      - name: Check Dependencies 
        run: npx dependency-check ./package.json --unused --no-dev ./src/bin/www
      - name: Run Retire JS
        run: npm run-script retire 
      - name: Sonar Cloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  ## Deploy if master
  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jo3-w3b-d3v-node-starter"
          heroku_email: "joe-evs196@hotmail.co.uk"
          usedocker: true