name: Continuous Deployment
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jo3-node-starter"
          heroku_email: "joe-evs196@hotmail.co.uk"
          usedocker: true
